{% set name = "hippynn" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hippynn-{{ version }}.tar.gz
  sha256: 2a0a6942b05d7627974ae904f1c0d4039d8dd6680f16db9178a889476dedb4ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer
  run:
    - python >={{ python_min }},<3.12
    - numpy
    - numba
    - pytorch
    - scipy

test:
  imports:
    - hippynn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lanl/hippynn
  summary: The hippynn python package - a modular library for atomistic machine learning with pytorch
  license: LicenseRef-US-Government OR BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lubbersnick
    - jan-janssen
