{% set name = "hippynn" %}
{% set version = "0.0.2a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hippynn-{{ version }}.tar.gz
  sha256: 3a553f60729e39f815e83efd1fd20426041583b1051ee021462aad25bb0ea4cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - numba
    - pytorch

test:
  imports:
    - hippynn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lanl/hippynn
  summary: The hippynn python package - a modular library for atomistic machine learning with pytorch
  license: LicenseRef-US-Government OR BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lubbersnick
    - jan-janssen
